
stages:
  - build

cache:
  paths:
    - vendor/
    - .yarn

build:
  stage: build
  image: node:16
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn code-check
  artifacts:
    paths:
      - docs

test:
  stage: build
  image: node:16
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs: []
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn test:unit

pages:
  stage: build
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle config set --local path 'vendor'
    - bundle install
    - bundle exec jekyll build -s docs -d public
  needs: [ build ]
  artifacts:
    paths:
      - public
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_TAG || $PUBLISH_DOC