stages:
  - build
  - test
  - pages

cache:
  paths:
    - vendor/
    - .yarn

build:
  stage: build
  image: node:18
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn build # Build lib directory
    - yarn build:browser # Build dist directory
    - yarn code-check
  artifacts:
    paths:
      - lib/
      - dist/
      - docs/

test:unit:
  stage: test
  image: node:18
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs: ["build"]
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn test:unit
  artifacts:
    reports:
      junit: junit.xml
    when: always

test:browser:
  stage: test
  image: node:18
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs: ["build"]
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn test:browser
  artifacts:
    reports:
      junit: junit.xml
    when: always

.test:integration:
  stage: test
  image: node:18
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs: ["build"]
  script:
    - yarn install --immutable --immutable-cache --check-cache
    - yarn test:integration
  artifacts:
    reports:
      junit: junit.xml
    when: always

pages:
  stage: pages
  image: ruby:3.3
  script:
    - gem install bundler
    - bundle config set --local path 'vendor'
    - bundle install
    - bundle exec jekyll build -s docs -d public
  needs: ["build"]
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG || $PUBLISH_DOC
